name: workflow_1
on: 
  push

jobs:
  test_compilation_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Test_echo
        run: |
          git clone https://github.com/sebritt/sobel_morpho.git
          cd sobel_morpho
          ls
          sudo apt-get install cmake -y
          cmake CMakeLists.txt
          
		
