name: compilation
on: 
  push

jobs:
  test_compilation_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation_Ubuntu
        run: |
          git clone https://github.com/sebritt/sobel_morpho.git
          cd sobel_morpho
          ls
          sudo apt-get update
          sudo apt-get install cmake -y
          sudo apt install libsdl2-2.0-0 libsdl2-gfx-1.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-net-2.0-0 libsdl2-ttf-2.0-0 -y
          sudo apt install libpthread-stubs0-dev -y
          cmake .

