name: compilation
on: 
  push

jobs:
  test_compilation_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation_Ubuntu
        run: |
          git clone https://github.com/sebritt/sobel_morpho.git
          cd sobel_morpho
          ls
          sudo apt-get update
          sudo apt-get install cmake -y
          cmake .

