name: compilation
on: 
  push

jobs:
  test_compilation_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation_Ubuntu
        run: |
          git clone https://github.com/sebritt/sobel_morpho.git
          cd sobel_morpho
          ls
          sudo apt-get update
          sudo apt-get install cmake -y
          sudo apt-get install libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev -y
          sudo apt-get install libpthread-stubs0-dev -y
          cmake .
          make
          timeout 20s ./Release/sobel

  test_compilation_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"'

      - name: Build Project
        run: |
          git clone https://github.com/sebritt/sobel_morpho.git
          cd sobel_morpho
          cmake .
          cmake --build . --config Release

      - name: Run Program with Timeout
        run: |
          # Start the program as a background job
          $process = Start-Process -NoNewWindow -FilePath ./Release/sobel -ArgumentList "" -PassThru
          # Wait for 20 seconds
          Start-Sleep -Seconds 20
          # Kill the process after 20 seconds
          $process | Stop-Process -Force

