name: compilation
on: 
  push

jobs:
  test_compilation_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation_Ubuntu
        run: |
          git clone https://github.com/sebritt/sobel_morpho.git
          cd sobel_morpho
          ls
          sudo apt-get update
          sudo apt-get install cmake -y
          sudo apt-get install libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev -y
          sudo apt-get install libpthread-stubs0-dev -y
          cmake .
          make
          ./Release/sobel

  test_compilation_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"'
          choco install mingw -y

      - name: Build Project
        run: |
          git clone https://github.com/sebritt/sobel_morpho.git
          cd sobel_morpho
          CMakeVS2013.bat

      - name: Run Program
        run: |
          # Get the absolute path to the executable
          Release/sobel.exe
          
